//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int FileID { get; set; }
        public string Base64 { get; set; }
        public string Extension { get; set; }
        public int WhistleID { get; set; }
    }
}
